Algoritmo "ex20"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/03/2023
Var
// Seção de Declarações das variáveis
   numero, imparPar: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite um numero inteiro: ")
   Leia(numero)

   Se (numero % 2 = 0) Entao
      Escreva("O numero ", numero, " é PAR.")
   Senao
      Escreva("O numero ", numero, " é IMPAR.")
   FimSe
   

Fimalgoritmo