Algoritmo "combinacoes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/04/2023
Var
   // Seção de Declarações das variáveis
   contadorUm, contadorDois: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   Para contadorUm := 1 ate 3 faca

      Para contadorDois := 1 ate 3 faca
         Escreval(contadorUm, contadorDois)
      FimPara

   FimPara


Fimalgoritmo