Algoritmo "CONTARDE10A0"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/04/2023
Var
   // Seção de Declarações das variáveis
   contador: inteiro



Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contador <- 10

   Enquanto (contador >= 0) Faca
      Escreval(contador)
      contador <- contador - 1
   FimEnquanto


Fimalgoritmo