Algoritmo "conta1a10comRepita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2023
Var
   // Seção de Declarações das variáveis
   cont: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   cont <- 1

   Repita
      Escreval(cont)
      cont <- cont + 1
   Ate (cont > 10)

Fimalgoritmo