Algoritmo "exAula07"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/03/2023
Var
   // Seção de Declarações das variáveis
   numero: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um número qualquer: ")
   Leia(numero)

   Se (numero % 2 = 0) Entao
      Escreval("O número", numero, " é PAR")
   SeNao
      Escreval("O número", numero, " é ÍMPAR")
   FimSe


Fimalgoritmo