Algoritmo "conversor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/02/2023
Var
// Seção de Declarações das variáveis
   Angulo, S: Real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Informe um angulo: ")
   Leia(Angulo)
   S <- Sen(GraupRad(Angulo))
   
   Escreva("O Seno de ", Angulo, " é igual a: ", S)


Fimalgoritmo