Algoritmo "funcoesAritmeticas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/02/2023
Var
// Seção de Declarações das variáveis 
   Absoluto: Inteiro
   Exponencial: Real
   Raiz: Real
   GrauParaRad: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Absoluto <- Abs (-50)
   Escreval(Absoluto)
   
   Escreval("")
   
   Exponencial <- Exp (9, 5)
   Escreva(Exponencial)
   
   Escreval("")
   
   Raiz <- Int(RaizQ(90))
   Escreval(Raiz)
   
   Escreval("")
   
   GrauParaRad <- Sen(GraupRad(90))
   Escreva(GrauParaRad)


Fimalgoritmo