Algoritmo "primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2023
Var
// Seção de Declarações das variáveis
   msg: caractere
   numero: inteiro
   numeroDois: real
   boolean: logico

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   msg <- "O meu número é:!"
   Escreval(msg)
   
   Escreval("Isso é meu primeiro programa: " + msg)
   
   numero <- 10
   Escreval(numero)
   
   numeroDois <- 0.5
   Escreval(numeroDois)
   
   boolean <- 12
   Escreval(boolean)

Fimalgoritmo