Algoritmo "valores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/02/2023
Var
// Seção de Declarações das variáveis 
   numeroUm: inteiro
   numeroDois: inteiro
   soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite um número: ")
   
   Leia(numeroUm)
   
   Escreva("Digite outro número: ")
   
   Leia(numeroDois)
   
   soma <- numeroUm + numeroDois
   
   Escreva("A soma entre ", numeroUm, " e", numeroDois, " é: ", soma)

Fimalgoritmo