Algoritmo "ex02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2023
Var
// Seção de Declarações das variáveis
   nome: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Qual seu nome? ", nome)
   Leia(nome)
   Escreval("Olá,", nome, " é um prazer conhecê-lo")


Fimalgoritmo