Algoritmo "ex03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2023
Var
// Seção de Declarações das variáveis
   nome: caractere
   salario: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Funcionário: ")
   Leia(nome)
   
   Escreval("Salário: ")
   Leia(salario)
   
   Escreva("O funcionário ", nome, " tem um salário de R$",salario, " por mês.")


Fimalgoritmo