Algoritmo "ex04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2023
Var
// Seção de Declarações das variáveis
   numeroUm: inteiro
   numeroDois: inteiro
   soma: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite o primeiro número: ")
   Leia(numeroUm)
   
   Escreva("Digite o segundo número: ")
   Leia(numeroDois)
   
   soma <- numeroUm + numeroDois
   
   Escreval("A soma entre os números ", numeroUm, " e", numeroDois, " é de: ", soma)


Fimalgoritmo