Algoritmo "ex07"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2023
Var
// Seção de Declarações das variáveis
   numero, dobro, tercaParte: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um número: ")
   Leia(numero)
   
   dobro <- numero * 2
   
   Escreval("O dobro de" ,numero, " é:", dobro)
   
   tercaParte <- numero / 3
   
   Escreval("A terça parte de " ,numero, "é: " ,tercaParte)


Fimalgoritmo