Algoritmo "ex09"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2023
Var
// Seção de Declarações das variáveis
   money: real
   dolar: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Quantos Reais você tem em uma carteira? ")
   Leia(Money)
   
   dolar <- money / 2.22
   
   Escreval("O dinheiro da sua carteira vale: US$" ,dolar:4:2, " dolares")


Fimalgoritmo