Algoritmo "ex15"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2023
Var
// Seção de Declarações das variáveis
   DT, SAL: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Quantos dias você trabalhou esse mês?")
   Leia(DT)
   
   SAL <- DT * (8 * 25)
   
   Escreval("Seu salário esse Mês foi de: ", SAL)


Fimalgoritmo