Algoritmo "ex29"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2023
Var
   // Seção de Declarações das variáveis
   nome: caractere
   salario, novoSalario: real
   anosTrabalhando: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Qual o nome do funcionário? ")
   Leia(nome)
   Escreval("Qual o salário atual do funcionário? ")
   Leia(salario)
   Escreval("A quantos anos ele trabalha na empresa? ")
   Leia(anosTrabalhando)
   
   escolha
   
   FimEscolha


Fimalgoritmo