Algoritmo "ex47"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/04/2023
Var
   // Seção de Declarações das variáveis
   contador, soma: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   soma <- 0
   para contador <- 500 ate 0 passo -50 faca
      soma <- soma + contador
   fimpara
   escreval("A soma dos números de 500 a 0 com decremento de 50 é: ", soma)


Fimalgoritmo